### ISSUE TITLE
GPU not found at Jetson Xavier

### ISSUE THREAD

**Issue by Kracozebr** [Deci-AI/infery-examples#25]
**Describe the bug**
Can not run your example with pytorch on Jetson Xavier. It does not see gpu.

**To Reproduce**
Run this exemple:
https://github.com/Deci-AI/infery-examples/blob/master/basic/predict_torch.py

**Expected behavior**
Expect to have benchmark on  my model.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04 Jetpack 4.6.1

**Smartphone (please complete the following information):**

**Additional context**
The issue is:
```
__init__ -INFO- Infery was successfully imported with 8 CPUS and 0 GPUS.
infery_manager -ERROR- Failed to register the model: Trying to initialize model for GPU execution, but GPU isn't available on this machine
Traceback (most recent call last):
  File "infery_benchmark.py", line 21, in <module>
    main()
  File "infery_benchmark.py", line 12, in main
    inference_hardware="gpu",
  File "/usr/local/lib/python3.6/dist-packages/infery/inference/infery_manager.py", line 238, in load
  File "/usr/local/lib/python3.6/dist-packages/infery/inference/infery_manager.py", line 193, in __verify_arguments_for_model_loading
infery.common.exceptions.InvalidInferenceHardware: Trying to initialize model for GPU execution, but GPU isn't available on this machine
```

**Comment by Kracozebr** [comment]
The reason is that infery does not see the gpu. I run in docker container:
```
>>> import infery
__init__ -INFO- Infery was successfully imported with 8 CPUS and 0 GPUS.
```

**Comment by avideci** [comment]
Hey @Kracozebr, Thanks for sharing the issue. 
- Which docker image are you using?
- Which version of infery did you install? What was the installation command?
  - Jetson installation instructions are available at https://github.com/Deci-AI/infery-examples/blob/master/docs/installation.md#jetson-installation .

**Comment by avideci** [comment]
@Kracozebr 
Your Jetson Orin host should to have jetson-stats (JTOP) installed on the host, I believe that is the problem.
It can be installed using "python3.8 -m pip install jetson-stats"

You can also use Docker:
`docker run --rm -v /run/jtop.sock:/run/jtop.sock --gpus=all -it <image-name-or-tag> bash`

And you can also mount the tensorrt from the host container, if you have TensorRT problems inside the container that you are using:
`-v /usr/lib/python3.6/dist-packages/tensorrt/:/lib/tensorrt `
